# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45de0de29fa4fbd61477409ae7bc3ca75790344fed09c45023c0a90e2bd9f10495dda52190233fcfa677b521e0c7497c39d13cee8ec19c1026e1b21ea46fa1f8

test:
  secret_key_base: ed42f451c8d0c13cf28c3d8aa302e5ddd703cdb1365b6a349be6f31824403961921efb0e55544a46e54faaa636423d102c7cdcf2d613f3f1cab0570e2a01d7ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
